#include <iostream>
#include <stdio.h>     
#include <stdlib.h>   
#include <Windows.h>
#include <time.h>
#include <fstream>
#include <vector>
#include <fcntl.h>
#include <string>
#include <optional>
#include <conio.h> 
#include <limits>
#include <random>
#include <sstream>
#include <io.h>
#include <fcntl.h>
#include <mutex>
#include <thread>
#include <algorithm>
#include <functional>
#include <locale>
#include <codecvt>
#include <memory>
#include <unordered_map>